### ISSUE TITLE
Incompatibility with v.1.1 and Java 8, Update 51

### ISSUE THREAD

**Issue by fhorvath** [x2on/gradle-cocoapods-plugin#2]
Hi, My team recently updated to 1.1 of your plugin and cocoapods 0.38.2. While the changes work for the rest of my team, I am seeing an error when I try to run a gradle command. The error I'm seeing is occurring on the line in our build.gradle file where we apply your plugin. The error I'm seeing is:

> java.lang.UnsupportedClassVersionError: de/felixschulze/gradle/CocoapodsPlugin : Unsupported major.minor version 51.0

I have recently updated Java to Java 8 update 51, and I think that might be what's causing this. Any insight into how I can resolve?

**Comment by x2on** [comment]
Could you please run `java -version` and post your output.

**Comment by fhorvath** [comment]
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)

**Comment by x2on** [comment]
That means your JRE 6 is default. Please setup JDK 8 or at least 7 as default.

**Comment by fhorvath** [comment]
Oh, my bad. I was using GUI tools for Java. Did not realize there was something wrong there. Will look into it.Thanks for the quick response!
