### ISSUE TITLE
Plugin version 1.1 was not found

### ISSUE THREAD

**Issue by adil-hussain-84** [x2on/gradle-cocoapods-plugin#3]
I just tried importing your plugin as follows...

    plugins {
        id "de.felixschulze.gradle.cocoapods" version "1.1"
    }

... but I got this error...

> Error:(3, 0) Plugin [id: 'de.felixschulze.gradle.cocoapods', version: '1.1'] was not found in any of the following sources:
> 
> - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
> - Gradle Central Plugin Repository (plugin 'de.felixschulze.gradle.cocoapods' has no version '1.1' - see https://plugins.gradle.org/plugin/de.felixschulze.gradle.cocoapods for available versions)

... looks like version 1.1 is not published to Gradle plugins? If I change version to "1.0" it works.

**Comment by adil-hussain-84** [comment]
I am able to import version "1.1" as the README suggests...

    buildscript {
        repositories {
            mavenCentral()
        }
        dependencies {
            classpath 'de.felixschulze.gradle:gradle-cocoapods-plugin:1.1'
        }
    }

    apply plugin: 'de.felixschulze.gradle.cocoapods'

... was just curious why the Gradle syntax as described in the question works for version 1.0 but not for 1.1.

**Comment by x2on** [comment]
No it's just published to maven central, not to gradle plugins.
